import { MigrationInterface, QueryRunner } from "typeorm";

export class AddCoApplicantToKycStatus1771222545281 implements MigrationInterface {
    name = 'AddCoApplicantToKycStatus1771222545281'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` DROP FOREIGN KEY \`FK_3d707ded770921157ef06da5059\``);
        await queryRunner.query(`DROP INDEX \`REL_3d707ded770921157ef06da505\` ON \`kyc_verification_status\``);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` ADD \`coApplicantId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` ADD \`mobileStatus\` enum ('PENDING', 'INITIATED', 'VERIFIED', 'FAILED') NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` ADD \`emailStatus\` enum ('PENDING', 'INITIATED', 'VERIFIED', 'FAILED') NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE \`permissions\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`approval_steps\` DROP FOREIGN KEY \`FK_1793f6b5d88249299d5e975b294\``);
        await queryRunner.query(`ALTER TABLE \`approval_steps\` CHANGE \`approverRoleId\` \`approverRoleId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`approval_steps\` CHANGE \`stepName\` \`stepName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`approval_flows\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`operations_checks\` DROP FOREIGN KEY \`FK_869ed96524bfae5ba9dd9552300\``);
        await queryRunner.query(`ALTER TABLE \`operations_checks\` CHANGE \`opsRemarks\` \`opsRemarks\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`operations_checks\` CHANGE \`opsUserId\` \`opsUserId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`approval_actions\` CHANGE \`comments\` \`comments\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`approval_instances\` DROP FOREIGN KEY \`FK_60c9e3247c9ee5b9b2f427e11f7\``);
        await queryRunner.query(`ALTER TABLE \`approval_instances\` DROP FOREIGN KEY \`FK_6b65e9c71ce92910f495238f850\``);
        await queryRunner.query(`ALTER TABLE \`approval_instances\` CHANGE \`creditSanctionId\` \`creditSanctionId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`approval_instances\` CHANGE \`operationsCheckId\` \`operationsCheckId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`approval_instances\` CHANGE \`currentApproverId\` \`currentApproverId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`approval_instances\` CHANGE \`remarks\` \`remarks\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`approval_instances\` CHANGE \`completedAt\` \`completedAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`credit_sanctions\` CHANGE \`conditions\` \`conditions\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`credit_sanctions\` CHANGE \`creditRemarks\` \`creditRemarks\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`post_sanctions\` CHANGE \`remarks\` \`remarks\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`invoices\` DROP FOREIGN KEY \`FK_ba32d48433269b9e7aefc0f0072\``);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`dueDate\` \`dueDate\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`invoiceFilePath\` \`invoiceFilePath\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`disbursedAmount\` \`disbursedAmount\` decimal(15,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`disbursedDate\` \`disbursedDate\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`createdByUserId\` \`createdByUserId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`rejectionReason\` \`rejectionReason\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`suppliers\` DROP FOREIGN KEY \`FK_963e5b95df84aef0659d60174d9\``);
        await queryRunner.query(`ALTER TABLE \`suppliers\` CHANGE \`address\` \`address\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`suppliers\` CHANGE \`gstNumber\` \`gstNumber\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`suppliers\` CHANGE \`panNumber\` \`panNumber\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`suppliers\` CHANGE \`createdByUserId\` \`createdByUserId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`suppliers\` CHANGE \`rejectionReason\` \`rejectionReason\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` DROP FOREIGN KEY \`FK_92f53db6c1dcb6b19afcea90145\``);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` DROP FOREIGN KEY \`FK_3501f186732c4e2d584fd82ccc6\``);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` DROP FOREIGN KEY \`FK_ecc366e5aaef2eccf547704d8dd\``);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` DROP FOREIGN KEY \`FK_096c1ec4fbe745a195fdcf2eba0\``);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` DROP FOREIGN KEY \`FK_24c497df9e237a9007306e9ec73\``);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` CHANGE \`customerId\` \`customerId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` CHANGE \`supplierId\` \`supplierId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` CHANGE \`invoiceId\` \`invoiceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` CHANGE \`currentApproverRoleId\` \`currentApproverRoleId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` CHANGE \`currentApproverRoleName\` \`currentApproverRoleName\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` CHANGE \`remarks\` \`remarks\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` CHANGE \`rejectionReason\` \`rejectionReason\` varchar(1000) NULL`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` CHANGE \`rejectedByUserId\` \`rejectedByUserId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` CHANGE \`rejectedDate\` \`rejectedDate\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` CHANGE \`completedDate\` \`completedDate\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` DROP FOREIGN KEY \`FK_6462a93ca2c035d2062f95d8b75\``);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` DROP FOREIGN KEY \`FK_c8e6ec02d8e07194d591181e2e2\``);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` DROP FOREIGN KEY \`FK_14328918670bf3eda5ef1595c2c\``);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` CHANGE \`supplierId\` \`supplierId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` CHANGE \`invoiceId\` \`invoiceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` CHANGE \`caseWorkflowId\` \`caseWorkflowId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` CHANGE \`previousStatus\` \`previousStatus\` enum ('draft', 'submitted', 'credit_l1_approved', 'credit_l2_approved', 'ceo_approved', 'md_pending_terms', 'md_terms_submitted', 'md_approved', 'ops_l1_review', 'ops_l1_approved', 'ops_l2_verified', 'ops_head_approved', 'completed', 'disbursed', 'rejected', 'credit_l2_approved', 'md_approved', 'ops_l1_approved', 'completed') NULL`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` CHANGE \`remarks\` \`remarks\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` CHANGE \`sanctionAmount\` \`sanctionAmount\` decimal(15,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` CHANGE \`tenure\` \`tenure\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` CHANGE \`interestRate\` \`interestRate\` decimal(5,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` CHANGE \`penalCharges\` \`penalCharges\` decimal(5,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` CHANGE \`processingFees\` \`processingFees\` decimal(5,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` CHANGE \`conditions\` \`conditions\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`co_applicants\` CHANGE \`email\` \`email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`co_applicants\` CHANGE \`gender\` \`gender\` enum ('Male', 'Female', 'Other') NULL`);
        await queryRunner.query(`ALTER TABLE \`kyc_details\` DROP FOREIGN KEY \`FK_ab58dee0afb2a683c6829cc565a\``);
        await queryRunner.query(`ALTER TABLE \`kyc_details\` CHANGE \`coApplicantId\` \`coApplicantId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`kyc_details\` CHANGE \`verifiedAt\` \`verifiedAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`kyc_details\` CHANGE \`verifiedBy\` \`verifiedBy\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`kyc_details\` CHANGE \`remarks\` \`remarks\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`contact_persons\` CHANGE \`email\` \`email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`contact_persons\` CHANGE \`designation\` \`designation\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`contact_persons\` CHANGE \`gender\` \`gender\` enum ('Male', 'Female', 'Other') NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`email\` \`email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`companyType\` \`companyType\` enum ('Proprietorship', 'Partnership', 'Pvt Ltd / Ltd', 'LLP') NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`companyName\` \`companyName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`gstNumber\` \`gstNumber\` varchar(15) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`companyMobile\` \`companyMobile\` varchar(20) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`companyEmail\` \`companyEmail\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`companyPan\` \`companyPan\` varchar(20) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`pan\` \`pan\` varchar(20) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`electricityBillNo\` \`electricityBillNo\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`customerName\` \`customerName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`customerCode\` \`customerCode\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`industryType\` \`industryType\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`annualTurnover\` \`annualTurnover\` decimal(15,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`lanId\` \`lanId\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`rejectionReason\` \`rejectionReason\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`pushedTo\` \`pushedTo\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`remarks\` \`remarks\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`bankAccountNo\` \`bankAccountNo\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`bankIfscCode\` \`bankIfscCode\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`bankName\` \`bankName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`bankBranch\` \`bankBranch\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`bankType\` \`bankType\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`documents\` DROP FOREIGN KEY \`FK_306974dcb26d433920a54a262a8\``);
        await queryRunner.query(`ALTER TABLE \`documents\` CHANGE \`coApplicantId\` \`coApplicantId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`documents\` CHANGE \`mimeType\` \`mimeType\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`documents\` CHANGE \`fileSize\` \`fileSize\` bigint NULL`);
        await queryRunner.query(`ALTER TABLE \`documents\` CHANGE \`verifiedBy\` \`verifiedBy\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`documents\` CHANGE \`verifiedAt\` \`verifiedAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`documents\` CHANGE \`issueDate\` \`issueDate\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`documents\` CHANGE \`expiryDate\` \`expiryDate\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`documents\` CHANGE \`remarks\` \`remarks\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`documents\` CHANGE \`rmRemarks\` \`rmRemarks\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`mobile\` \`mobile\` varchar(20) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`defaultRole\` \`defaultRole\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` CHANGE \`assignedBy\` \`assignedBy\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`sanction_limit_history\` CHANGE \`penalCharges\` \`penalCharges\` decimal(5,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`sanction_limit_history\` CHANGE \`processingFees\` \`processingFees\` decimal(5,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`sanction_limit_history\` CHANGE \`conditions\` \`conditions\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`sanction_limit_history\` CHANGE \`remarks\` \`remarks\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`otp_sessions\` DROP FOREIGN KEY \`FK_7efbcb19474cda835784a42807c\``);
        await queryRunner.query(`ALTER TABLE \`otp_sessions\` CHANGE \`customerId\` \`customerId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` CHANGE \`aadhaarTransactionId\` \`aadhaarTransactionId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` CHANGE \`aadhaarName\` \`aadhaarName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` CHANGE \`aadhaarMaskedNumber\` \`aadhaarMaskedNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` CHANGE \`aadhaarDob\` \`aadhaarDob\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` CHANGE \`aadhaarAddress\` \`aadhaarAddress\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` DROP COLUMN \`panApiRequest\``);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` ADD \`panApiRequest\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` DROP COLUMN \`panApiResponse\``);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` ADD \`panApiResponse\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` DROP COLUMN \`gstApiRequest\``);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` ADD \`gstApiRequest\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` DROP COLUMN \`gstApiResponse\``);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` ADD \`gstApiResponse\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` DROP COLUMN \`aadhaarApiRequest\``);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` ADD \`aadhaarApiRequest\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` DROP COLUMN \`aadhaarApiResponse\``);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` ADD \`aadhaarApiResponse\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` DROP COLUMN \`bureauApiRequest\``);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` ADD \`bureauApiRequest\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` DROP COLUMN \`bureauApiResponse\``);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` ADD \`bureauApiResponse\` json NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_d78beff177bc8334f0d3a4675f\` ON \`kyc_verification_status\` (\`customerId\`, \`coApplicantId\`)`);
        await queryRunner.query(`ALTER TABLE \`approval_steps\` ADD CONSTRAINT \`FK_1793f6b5d88249299d5e975b294\` FOREIGN KEY (\`approverRoleId\`) REFERENCES \`roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`operations_checks\` ADD CONSTRAINT \`FK_869ed96524bfae5ba9dd9552300\` FOREIGN KEY (\`opsUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`approval_instances\` ADD CONSTRAINT \`FK_60c9e3247c9ee5b9b2f427e11f7\` FOREIGN KEY (\`creditSanctionId\`) REFERENCES \`credit_sanctions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`approval_instances\` ADD CONSTRAINT \`FK_6b65e9c71ce92910f495238f850\` FOREIGN KEY (\`operationsCheckId\`) REFERENCES \`operations_checks\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invoices\` ADD CONSTRAINT \`FK_ba32d48433269b9e7aefc0f0072\` FOREIGN KEY (\`createdByUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`suppliers\` ADD CONSTRAINT \`FK_963e5b95df84aef0659d60174d9\` FOREIGN KEY (\`createdByUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` ADD CONSTRAINT \`FK_92f53db6c1dcb6b19afcea90145\` FOREIGN KEY (\`customerId\`) REFERENCES \`customers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` ADD CONSTRAINT \`FK_3501f186732c4e2d584fd82ccc6\` FOREIGN KEY (\`supplierId\`) REFERENCES \`suppliers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` ADD CONSTRAINT \`FK_ecc366e5aaef2eccf547704d8dd\` FOREIGN KEY (\`invoiceId\`) REFERENCES \`invoices\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` ADD CONSTRAINT \`FK_096c1ec4fbe745a195fdcf2eba0\` FOREIGN KEY (\`currentApproverRoleId\`) REFERENCES \`roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` ADD CONSTRAINT \`FK_24c497df9e237a9007306e9ec73\` FOREIGN KEY (\`rejectedByUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` ADD CONSTRAINT \`FK_6462a93ca2c035d2062f95d8b75\` FOREIGN KEY (\`supplierId\`) REFERENCES \`suppliers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` ADD CONSTRAINT \`FK_c8e6ec02d8e07194d591181e2e2\` FOREIGN KEY (\`invoiceId\`) REFERENCES \`invoices\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` ADD CONSTRAINT \`FK_14328918670bf3eda5ef1595c2c\` FOREIGN KEY (\`caseWorkflowId\`) REFERENCES \`case_workflows\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`kyc_details\` ADD CONSTRAINT \`FK_ab58dee0afb2a683c6829cc565a\` FOREIGN KEY (\`coApplicantId\`) REFERENCES \`co_applicants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`documents\` ADD CONSTRAINT \`FK_306974dcb26d433920a54a262a8\` FOREIGN KEY (\`coApplicantId\`) REFERENCES \`co_applicants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`otp_sessions\` ADD CONSTRAINT \`FK_7efbcb19474cda835784a42807c\` FOREIGN KEY (\`customerId\`) REFERENCES \`customers\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` ADD CONSTRAINT \`FK_2addf9610f989ac5bfdcc51e195\` FOREIGN KEY (\`coApplicantId\`) REFERENCES \`co_applicants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` ADD CONSTRAINT \`FK_3d707ded770921157ef06da5059\` FOREIGN KEY (\`customerId\`) REFERENCES \`customers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` DROP FOREIGN KEY \`FK_2addf9610f989ac5bfdcc51e195\``);
        await queryRunner.query(`ALTER TABLE \`otp_sessions\` DROP FOREIGN KEY \`FK_7efbcb19474cda835784a42807c\``);
        await queryRunner.query(`ALTER TABLE \`documents\` DROP FOREIGN KEY \`FK_306974dcb26d433920a54a262a8\``);
        await queryRunner.query(`ALTER TABLE \`kyc_details\` DROP FOREIGN KEY \`FK_ab58dee0afb2a683c6829cc565a\``);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` DROP FOREIGN KEY \`FK_14328918670bf3eda5ef1595c2c\``);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` DROP FOREIGN KEY \`FK_c8e6ec02d8e07194d591181e2e2\``);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` DROP FOREIGN KEY \`FK_6462a93ca2c035d2062f95d8b75\``);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` DROP FOREIGN KEY \`FK_24c497df9e237a9007306e9ec73\``);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` DROP FOREIGN KEY \`FK_096c1ec4fbe745a195fdcf2eba0\``);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` DROP FOREIGN KEY \`FK_ecc366e5aaef2eccf547704d8dd\``);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` DROP FOREIGN KEY \`FK_3501f186732c4e2d584fd82ccc6\``);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` DROP FOREIGN KEY \`FK_92f53db6c1dcb6b19afcea90145\``);
        await queryRunner.query(`ALTER TABLE \`suppliers\` DROP FOREIGN KEY \`FK_963e5b95df84aef0659d60174d9\``);
        await queryRunner.query(`ALTER TABLE \`invoices\` DROP FOREIGN KEY \`FK_ba32d48433269b9e7aefc0f0072\``);
        await queryRunner.query(`ALTER TABLE \`approval_instances\` DROP FOREIGN KEY \`FK_6b65e9c71ce92910f495238f850\``);
        await queryRunner.query(`ALTER TABLE \`approval_instances\` DROP FOREIGN KEY \`FK_60c9e3247c9ee5b9b2f427e11f7\``);
        await queryRunner.query(`ALTER TABLE \`operations_checks\` DROP FOREIGN KEY \`FK_869ed96524bfae5ba9dd9552300\``);
        await queryRunner.query(`ALTER TABLE \`approval_steps\` DROP FOREIGN KEY \`FK_1793f6b5d88249299d5e975b294\``);
        await queryRunner.query(`DROP INDEX \`IDX_d78beff177bc8334f0d3a4675f\` ON \`kyc_verification_status\``);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` DROP COLUMN \`bureauApiResponse\``);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` ADD \`bureauApiResponse\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` DROP COLUMN \`bureauApiRequest\``);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` ADD \`bureauApiRequest\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` DROP COLUMN \`aadhaarApiResponse\``);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` ADD \`aadhaarApiResponse\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` DROP COLUMN \`aadhaarApiRequest\``);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` ADD \`aadhaarApiRequest\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` DROP COLUMN \`gstApiResponse\``);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` ADD \`gstApiResponse\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` DROP COLUMN \`gstApiRequest\``);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` ADD \`gstApiRequest\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` DROP COLUMN \`panApiResponse\``);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` ADD \`panApiResponse\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` DROP COLUMN \`panApiRequest\``);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` ADD \`panApiRequest\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` CHANGE \`aadhaarAddress\` \`aadhaarAddress\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` CHANGE \`aadhaarDob\` \`aadhaarDob\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` CHANGE \`aadhaarMaskedNumber\` \`aadhaarMaskedNumber\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` CHANGE \`aadhaarName\` \`aadhaarName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` CHANGE \`aadhaarTransactionId\` \`aadhaarTransactionId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`otp_sessions\` CHANGE \`customerId\` \`customerId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`otp_sessions\` ADD CONSTRAINT \`FK_7efbcb19474cda835784a42807c\` FOREIGN KEY (\`customerId\`) REFERENCES \`customers\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sanction_limit_history\` CHANGE \`remarks\` \`remarks\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sanction_limit_history\` CHANGE \`conditions\` \`conditions\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sanction_limit_history\` CHANGE \`processingFees\` \`processingFees\` decimal(5,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sanction_limit_history\` CHANGE \`penalCharges\` \`penalCharges\` decimal(5,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` CHANGE \`assignedBy\` \`assignedBy\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`defaultRole\` \`defaultRole\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`mobile\` \`mobile\` varchar(20) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`documents\` CHANGE \`rmRemarks\` \`rmRemarks\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`documents\` CHANGE \`remarks\` \`remarks\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`documents\` CHANGE \`expiryDate\` \`expiryDate\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`documents\` CHANGE \`issueDate\` \`issueDate\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`documents\` CHANGE \`verifiedAt\` \`verifiedAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`documents\` CHANGE \`verifiedBy\` \`verifiedBy\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`documents\` CHANGE \`fileSize\` \`fileSize\` bigint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`documents\` CHANGE \`mimeType\` \`mimeType\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`documents\` CHANGE \`coApplicantId\` \`coApplicantId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`documents\` ADD CONSTRAINT \`FK_306974dcb26d433920a54a262a8\` FOREIGN KEY (\`coApplicantId\`) REFERENCES \`co_applicants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`bankType\` \`bankType\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`bankBranch\` \`bankBranch\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`bankName\` \`bankName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`bankIfscCode\` \`bankIfscCode\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`bankAccountNo\` \`bankAccountNo\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`remarks\` \`remarks\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`pushedTo\` \`pushedTo\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`rejectionReason\` \`rejectionReason\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`lanId\` \`lanId\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`annualTurnover\` \`annualTurnover\` decimal(15,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`industryType\` \`industryType\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`customerCode\` \`customerCode\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`customerName\` \`customerName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`electricityBillNo\` \`electricityBillNo\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`pan\` \`pan\` varchar(20) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`companyPan\` \`companyPan\` varchar(20) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`companyEmail\` \`companyEmail\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`companyMobile\` \`companyMobile\` varchar(20) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`gstNumber\` \`gstNumber\` varchar(15) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`companyName\` \`companyName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`companyType\` \`companyType\` enum ('Proprietorship', 'Partnership', 'Pvt Ltd / Ltd', 'LLP') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`email\` \`email\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`contact_persons\` CHANGE \`gender\` \`gender\` enum ('Male', 'Female', 'Other') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`contact_persons\` CHANGE \`designation\` \`designation\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`contact_persons\` CHANGE \`email\` \`email\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`kyc_details\` CHANGE \`remarks\` \`remarks\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`kyc_details\` CHANGE \`verifiedBy\` \`verifiedBy\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`kyc_details\` CHANGE \`verifiedAt\` \`verifiedAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`kyc_details\` CHANGE \`coApplicantId\` \`coApplicantId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`kyc_details\` ADD CONSTRAINT \`FK_ab58dee0afb2a683c6829cc565a\` FOREIGN KEY (\`coApplicantId\`) REFERENCES \`co_applicants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`co_applicants\` CHANGE \`gender\` \`gender\` enum ('Male', 'Female', 'Other') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`co_applicants\` CHANGE \`email\` \`email\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` CHANGE \`conditions\` \`conditions\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` CHANGE \`processingFees\` \`processingFees\` decimal(5,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` CHANGE \`penalCharges\` \`penalCharges\` decimal(5,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` CHANGE \`interestRate\` \`interestRate\` decimal(5,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` CHANGE \`tenure\` \`tenure\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` CHANGE \`sanctionAmount\` \`sanctionAmount\` decimal(15,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` CHANGE \`remarks\` \`remarks\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` CHANGE \`previousStatus\` \`previousStatus\` enum ('draft', 'submitted', 'credit_l1_approved', 'credit_l2_approved', 'ceo_approved', 'md_pending_terms', 'md_terms_submitted', 'md_approved', 'ops_l1_review', 'ops_l1_approved', 'ops_l2_verified', 'ops_head_approved', 'completed', 'disbursed', 'rejected', 'credit_l2_approved', 'md_approved', 'ops_l1_approved', 'completed') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` CHANGE \`caseWorkflowId\` \`caseWorkflowId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` CHANGE \`invoiceId\` \`invoiceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` CHANGE \`supplierId\` \`supplierId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` ADD CONSTRAINT \`FK_14328918670bf3eda5ef1595c2c\` FOREIGN KEY (\`caseWorkflowId\`) REFERENCES \`case_workflows\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` ADD CONSTRAINT \`FK_c8e6ec02d8e07194d591181e2e2\` FOREIGN KEY (\`invoiceId\`) REFERENCES \`invoices\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_status_history\` ADD CONSTRAINT \`FK_6462a93ca2c035d2062f95d8b75\` FOREIGN KEY (\`supplierId\`) REFERENCES \`suppliers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` CHANGE \`completedDate\` \`completedDate\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` CHANGE \`rejectedDate\` \`rejectedDate\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` CHANGE \`rejectedByUserId\` \`rejectedByUserId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` CHANGE \`rejectionReason\` \`rejectionReason\` varchar(1000) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` CHANGE \`remarks\` \`remarks\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` CHANGE \`currentApproverRoleName\` \`currentApproverRoleName\` varchar(500) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` CHANGE \`currentApproverRoleId\` \`currentApproverRoleId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` CHANGE \`invoiceId\` \`invoiceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` CHANGE \`supplierId\` \`supplierId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` CHANGE \`customerId\` \`customerId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` ADD CONSTRAINT \`FK_24c497df9e237a9007306e9ec73\` FOREIGN KEY (\`rejectedByUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` ADD CONSTRAINT \`FK_096c1ec4fbe745a195fdcf2eba0\` FOREIGN KEY (\`currentApproverRoleId\`) REFERENCES \`roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` ADD CONSTRAINT \`FK_ecc366e5aaef2eccf547704d8dd\` FOREIGN KEY (\`invoiceId\`) REFERENCES \`invoices\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` ADD CONSTRAINT \`FK_3501f186732c4e2d584fd82ccc6\` FOREIGN KEY (\`supplierId\`) REFERENCES \`suppliers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_workflows\` ADD CONSTRAINT \`FK_92f53db6c1dcb6b19afcea90145\` FOREIGN KEY (\`customerId\`) REFERENCES \`customers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`suppliers\` CHANGE \`rejectionReason\` \`rejectionReason\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`suppliers\` CHANGE \`createdByUserId\` \`createdByUserId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`suppliers\` CHANGE \`panNumber\` \`panNumber\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`suppliers\` CHANGE \`gstNumber\` \`gstNumber\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`suppliers\` CHANGE \`address\` \`address\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`suppliers\` ADD CONSTRAINT \`FK_963e5b95df84aef0659d60174d9\` FOREIGN KEY (\`createdByUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`rejectionReason\` \`rejectionReason\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`createdByUserId\` \`createdByUserId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`disbursedDate\` \`disbursedDate\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`disbursedAmount\` \`disbursedAmount\` decimal(15,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`invoiceFilePath\` \`invoiceFilePath\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`dueDate\` \`dueDate\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` ADD CONSTRAINT \`FK_ba32d48433269b9e7aefc0f0072\` FOREIGN KEY (\`createdByUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post_sanctions\` CHANGE \`remarks\` \`remarks\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`credit_sanctions\` CHANGE \`creditRemarks\` \`creditRemarks\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`credit_sanctions\` CHANGE \`conditions\` \`conditions\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`approval_instances\` CHANGE \`completedAt\` \`completedAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`approval_instances\` CHANGE \`remarks\` \`remarks\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`approval_instances\` CHANGE \`currentApproverId\` \`currentApproverId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`approval_instances\` CHANGE \`operationsCheckId\` \`operationsCheckId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`approval_instances\` CHANGE \`creditSanctionId\` \`creditSanctionId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`approval_instances\` ADD CONSTRAINT \`FK_6b65e9c71ce92910f495238f850\` FOREIGN KEY (\`operationsCheckId\`) REFERENCES \`operations_checks\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`approval_instances\` ADD CONSTRAINT \`FK_60c9e3247c9ee5b9b2f427e11f7\` FOREIGN KEY (\`creditSanctionId\`) REFERENCES \`credit_sanctions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`approval_actions\` CHANGE \`comments\` \`comments\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`operations_checks\` CHANGE \`opsUserId\` \`opsUserId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`operations_checks\` CHANGE \`opsRemarks\` \`opsRemarks\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`operations_checks\` ADD CONSTRAINT \`FK_869ed96524bfae5ba9dd9552300\` FOREIGN KEY (\`opsUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`approval_flows\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`approval_steps\` CHANGE \`stepName\` \`stepName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`approval_steps\` CHANGE \`approverRoleId\` \`approverRoleId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`approval_steps\` ADD CONSTRAINT \`FK_1793f6b5d88249299d5e975b294\` FOREIGN KEY (\`approverRoleId\`) REFERENCES \`roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`permissions\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` DROP COLUMN \`emailStatus\``);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` DROP COLUMN \`mobileStatus\``);
        await queryRunner.query(`ALTER TABLE \`kyc_verification_status\` DROP COLUMN \`coApplicantId\``);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_3d707ded770921157ef06da505\` ON \`kyc_verification_status\` (\`customerId\`)`);
    }

}
